### PR TITLE
Optimize code for dnf-2.0

### PR DESCRIPTION
**Pull request by j-mracek**

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@j-mracek Rather than trying to reference private APIs that have no guarantee of availability, how about actually making public APIs that programs like dnfdaemon can use for dnf 2.0?

**Comment by j-mracek** [comment]
It is correct, this is hot fix that use private method. The code use wide range of dnf calls that is not marked as api, therefore it can be any time broken. But this information is not a secret. Therefore I can only recommend to start deeper refactoring.

**Comment by timlau** [comment]
Merged, Agree that in the ideal world, every thing need was in the public API, but currently that is not the case, i will use as much public API as i can and try to document the use of private api and limit it as much as possible.

**Comment by j-mracek** [comment]
If we will know that some function is externally needed, we can mark it as api or try to provide other solution (information can be passed by Bugzilla request).

**Comment by genodeftest** [comment]
@j-mracek : https://bugzilla.redhat.com/show_bug.cgi?id=1332067 would be nice to see fixed. Haven't looked deeper so there is more to come.

**Comment by j-mracek** [comment]
Ok, I am working on it.

**Comment by genodeftest** [comment]
@j-mracek : Thanks for fixing hawkey!

**Comment by j-mracek** [comment]
@genodeftest Not my work but @ignatenkobrain

**Comment by ignatenkobrain** [comment]
@genodeftest unfortunately it's still not fixed (I just found workaround), though there is a bug in DNF itself.

**Pull request merged**
